node_layout_builder.content_type.*:
  type: config_entity
  label: 'Content types and Node Layout Builder enabled'
  mapping:
    enabled:
      type: boolean
      label: 'Whether Node Layout Builder is enabled'
